### ISSUE TITLE
build it fail

### ISSUE THREAD

**Issue by imhsz** [kiwibrowser/src#140]
when i build it,and run '# gn gen out/android_arm',output:
Writing build/secondary/third_party/android_tools/google_play_services_basement_java.info
Writing third_party/android_support_test_runner/rules_java.info
Writing build/secondary/third_party/android_tools/google_play_services_tasks_java.info
ERROR at //build/config/android/rules.gni:3210:7: Script returned non-zero exit code.
      exec_script("//build/android/gyp/aar.py",
      ^----------
Current dir: /mnt/d/work/browser/kiwi-androidwithcrx/src/out/android_arm/
Command: python -- /mnt/d/work/browser/kiwi-androidwithcrx/src/build/android/gyp/aar.py list ../../third_party/android_support_test_runner/lib/rules.aar --output ../../third_party/android_support_test_runner/rules_java.info
Returned 1.
stderr:

Traceback (most recent call last):
  File "/mnt/d/work/browser/kiwi-androidwithcrx/src/build/android/gyp/aar.py", line 135, in <module>
    sys.exit(main())
  File "/mnt/d/work/browser/kiwi-androidwithcrx/src/build/android/gyp/aar.py", line 131, in main
    args.output.write(_CreateInfo(args.aar_file))
  File "/mnt/d/work/browser/kiwi-androidwithcrx/src/build/android/gyp/aar.py", line 52, in _CreateInfo
    with zipfile.ZipFile(aar_file) as z:
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

See //third_party/android_support_test_runner/BUILD.gn:21:1: whence it was called.
android_aar_prebuilt("rules_java") {
^-----------------------------------
See //build/config/android/internal_rules.gni:117:23: which caused the file to be included.
            deps += [ "${_target_label}__build_config" ]
                      ^-------------------------------
==========
Who can help me?

**Comment by imhsz** [comment]
The error is appear in window.And it's work in linux. The 'ln -s' file is not supported in window.
